sudo: false

branches:
  only:
    - v2.5.0-dev

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

script:
  - ./deploy_docs.sh
